## Numpy Array Operations

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print("Basic Slicing", arr[2:7:2])
print("Basic Slicing", arr[-1::-2])

Basic Slicing [3 5 7]
Basic Slicing [10  8  6  4  2]


In [3]:
"""Indexing on 2D array"""

arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d[1,2])

print("Entire Row: ",arr_2d[1])
print("Entire Coloum: ",arr_2d[:,1])

6
Entire Row:  [4 5 6]
Entire Coloum:  [2 5 8]


In [4]:
"""Sorting"""

unsorted = np.array([3,1,58,9,2,6,7,92,0,14,9,45])
print(np.sort(unsorted))

arr_2d_unsorted = np.array([[3,1],[1,2],[2,3]])
print(arr_2d_unsorted)
print(np.sort(arr_2d_unsorted,axis=0)) # axis zero is the coloum wise sorting, axis one is the row wise sorting

[ 0  1  2  3  6  7  9  9 14 45 58 92]
[[3 1]
 [1 2]
 [2 3]]
[[1 1]
 [2 2]
 [3 3]]


In [5]:
"""Filtering"""

numbers = np.arange(11)
# print(numbers)

even = numbers[numbers % 2 == 0] # this will always be 1D data
print(numbers)
print(even)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]


In [6]:
"""Some Numbers"""

numbers = np.array([[1,2,3],[4,5,6],[7,8,9]])

some_num = numbers[numbers[1]>1]

print(some_num)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
"""Filter with mask"""

numbers = np.array([[1,2,3],[4,5,6],[7,8,9]])
mask = numbers > 5 # will return a matrix of true and false
print(mask)

print(numbers[mask]) # this will be an 1D array

[[False False False]
 [False False  True]
 [ True  True  True]]
[6 7 8 9]


In [8]:
""" Fancy Indexing vs np.where()"""
numbers = np.arange(11)
indices = [0,2,4]

print(numbers[indices])

where_Result = np.where(numbers > 5)

mask = numbers > 5
print(mask)
print(where_Result)
print(numbers[where_Result])


[0 2 4]
[False False False False False False  True  True  True  True  True]
(array([ 6,  7,  8,  9, 10]),)
[ 6  7  8  9 10]


In [9]:
"""Condition array"""
numbers = np.arange(25)
condition_Array = np.where(numbers> 5,numbers,numbers*2)
print(condition_Array)
print(numbers[condition_Array])

[ 0  2  4  6  8 10  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
[ 0  2  4  6  8 10  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [10]:
"""Adding and Removing"""

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


In [11]:
"""Array Compatablitiy"""

a = np.array([1,2,3])
b = np.array([4,5,6,7])
c = np.array([9,55,3])

print(a.shape == b.shape)

False


In [12]:
"""Adding Rows"""

a = np.array([[2,3],[4,5]])
b= np.array([[0,1]])

with_new_row = np.vstack([a,b])
print(b)
print(with_new_row)


[[0 1]]
[[2 3]
 [4 5]
 [0 1]]


In [ ]:
"""Adding Coloums"""
new_col = np.array([[1],[2]])

with_new_col = np.hstack([a,new_col])
print(with_new_col)

[[2 3 1]
 [4 5 2]]


In [ ]:
"""Deleting data"""

arr = np.array([1,2,3,4,5,6,7,8,9,10])

deleted = np.delete(arr,2)
print(deleted)


[ 1  2  4  5  6  7  8  9 10]
