In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [11]:
# Data structure: [restaurant_id, 2021, 2022, 2023, 2024]
sales_data = np.array([
    [1, 150000, 180000, 220000, 250000],  # Paradise Biryani
    [2, 120000, 140000, 160000, 190000],  # Beijing Bites
    [3, 200000, 230000, 260000, 300000],  # Pizza Hub
    [4, 180000, 210000, 240000, 270000],  # Burger Point
    [5, 160000, 185000, 205000, 230000]   # Chai Point
])

print("==============Sales Analysis==================")

# print(sales_data.shape)
# print(sales_data.ndim)
# print(sales_data.size)

# print(sales_data)

print("The Slaes data of first three resturants are \n\n", sales_data[:3])

==============Sales Analysis==================
The Slaes data of first three resturants are 

 [[     1 150000 180000 220000 250000]
 [     2 120000 140000 160000 190000]
 [     3 200000 230000 260000 300000]]
