## Numpy array and basics

In [7]:
import numpy as np

In [8]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]]) # numpy will always take only one main list
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [9]:
"""
    List vs numpy array
"""

py_list = [1,2,3]
print(py_list*3) # this will end up becoming thrice in length and 1 2 3  will be repeated thrice

np_array = np.array([1,2,3])
print(np_array*2)

np_Arr = np.arange(10000000)
print(np_Arr)

[1, 2, 3, 1, 2, 3, 1, 2, 3]
[2 4 6]
[      0       1       2 ... 9999997 9999998 9999999]


In [10]:
zeros = np.zeros([3,4])
print(zeros)

ones = np.ones([3,4])
print(ones)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [11]:
full = np.full([2,2],7)
print(full)

[[7 7]
 [7 7]]


In [12]:
random = np.random.random([2,3])
print(random)

[[0.61559903 0.76595907 0.69745293]
 [0.14301849 0.09047716 0.18228439]]


In [13]:
sequemce = np.arange(0,10,2)
print(sequemce)

[0 2 4 6 8]


In [14]:
"""Vector matrix and Tensor"""

vector = np.array([1,2,3])
print(vector)

matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])

print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [15]:
"""Array Properties"""

arr = np.array([[1,2,3],[4,5,6],[1,2,3]])

print("Shape of array: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Dtype: ", arr.dtype)

Shape of array:  (3, 3)
Dimension:  2
Size:  9
Dtype:  int64


In [18]:
"""Array Reshaping"""
arr = np.arange(12)
print("Orignial Array: ", arr)

reshaped = arr.reshape(3,4)
print("\n Reshaped array",reshaped)

flattened = reshaped.flatten()
print("\n Flattened array: ", flattened)

# returns view , instead of copy
"""View baically operates on the same data given but copy creates a new clone of the data"""
raveled = reshaped.ravel() # Ravel works the same way as flatten but works on view meaning it cahnges the data
print("\n Raveled array: ", raveled)

"""Transpose"""

transpose = reshaped.T
print("\n Transposed Array: \n", transpose)


Orignial Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Raveled array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed Array: 
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


In [17]:
"""https://www.youtube.com/watch?v=x7ULDYs4X84"""

'https://www.youtube.com/watch?v=x7ULDYs4X84'

## Phase 2